export const CATEGORY_COLOR_KEYS = [
    "indigo",
    "emerald",
    "rose",
    "amber",
    "cyan",
    "violet",
    "orange",
    "teal",
];

export const CATEGORY_COLORS_MAP = {
    indigo: {
        key: "indigo",
        label: "Indigo",
        swatch: "bg-indigo-500",
        swatchRing: "ring-indigo-300",
        border: "border-l-indigo-400",
        borderHover: "hover:border-l-indigo-500",
        bg: "bg-indigo-50",
        bgLight: "bg-indigo-50/60",
        iconBg: "bg-indigo-100",
        iconColor: "text-indigo-600",
        progressBar: "bg-indigo-500",
        addBtnText: "text-indigo-600",
        addBtnHover: "hover:bg-indigo-50",
        txBorderL: "border-l-indigo-300",
        txBorderLHover: "hover:border-l-indigo-400",
    },
    emerald: {
        key: "emerald",
        label: "Verde",
        swatch: "bg-emerald-500",
        swatchRing: "ring-emerald-300",
        border: "border-l-emerald-400",
        borderHover: "hover:border-l-emerald-500",
        bg: "bg-emerald-50",
        bgLight: "bg-emerald-50/60",
        iconBg: "bg-emerald-100",
        iconColor: "text-emerald-600",
        progressBar: "bg-emerald-500",
        addBtnText: "text-emerald-600",
        addBtnHover: "hover:bg-emerald-50",
        txBorderL: "border-l-emerald-300",
        txBorderLHover: "hover:border-l-emerald-400",
    },
    rose: {
        key: "rose",
        label: "Rosa",
        swatch: "bg-rose-500",
        swatchRing: "ring-rose-300",
        border: "border-l-rose-400",
        borderHover: "hover:border-l-rose-500",
        bg: "bg-rose-50",
        bgLight: "bg-rose-50/60",
        iconBg: "bg-rose-100",
        iconColor: "text-rose-600",
        progressBar: "bg-rose-500",
        addBtnText: "text-rose-600",
        addBtnHover: "hover:bg-rose-50",
        txBorderL: "border-l-rose-300",
        txBorderLHover: "hover:border-l-rose-400",
    },
    amber: {
        key: "amber",
        label: "Ambra",
        swatch: "bg-amber-500",
        swatchRing: "ring-amber-300",
        border: "border-l-amber-400",
        borderHover: "hover:border-l-amber-500",
        bg: "bg-amber-50",
        bgLight: "bg-amber-50/60",
        iconBg: "bg-amber-100",
        iconColor: "text-amber-600",
        progressBar: "bg-amber-500",
        addBtnText: "text-amber-600",
        addBtnHover: "hover:bg-amber-50",
        txBorderL: "border-l-amber-300",
        txBorderLHover: "hover:border-l-amber-400",
    },
    cyan: {
        key: "cyan",
        label: "Ciano",
        swatch: "bg-cyan-500",
        swatchRing: "ring-cyan-300",
        border: "border-l-cyan-400",
        borderHover: "hover:border-l-cyan-500",
        bg: "bg-cyan-50",
        bgLight: "bg-cyan-50/60",
        iconBg: "bg-cyan-100",
        iconColor: "text-cyan-600",
        progressBar: "bg-cyan-500",
        addBtnText: "text-cyan-600",
        addBtnHover: "hover:bg-cyan-50",
        txBorderL: "border-l-cyan-300",
        txBorderLHover: "hover:border-l-cyan-400",
    },
    violet: {
        key: "violet",
        label: "Viola",
        swatch: "bg-violet-500",
        swatchRing: "ring-violet-300",
        border: "border-l-violet-400",
        borderHover: "hover:border-l-violet-500",
        bg: "bg-violet-50",
        bgLight: "bg-violet-50/60",
        iconBg: "bg-violet-100",
        iconColor: "text-violet-600",
        progressBar: "bg-violet-500",
        addBtnText: "text-violet-600",
        addBtnHover: "hover:bg-violet-50",
        txBorderL: "border-l-violet-300",
        txBorderLHover: "hover:border-l-violet-400",
    },
    orange: {
        key: "orange",
        label: "Arancione",
        swatch: "bg-orange-500",
        swatchRing: "ring-orange-300",
        border: "border-l-orange-400",
        borderHover: "hover:border-l-orange-500",
        bg: "bg-orange-50",
        bgLight: "bg-orange-50/60",
        iconBg: "bg-orange-100",
        iconColor: "text-orange-600",
        progressBar: "bg-orange-500",
        addBtnText: "text-orange-600",
        addBtnHover: "hover:bg-orange-50",
        txBorderL: "border-l-orange-300",
        txBorderLHover: "hover:border-l-orange-400",
    },
    teal: {
        key: "teal",
        label: "Turchese",
        swatch: "bg-teal-500",
        swatchRing: "ring-teal-300",
        border: "border-l-teal-400",
        borderHover: "hover:border-l-teal-500",
        bg: "bg-teal-50",
        bgLight: "bg-teal-50/60",
        iconBg: "bg-teal-100",
        iconColor: "text-teal-600",
        progressBar: "bg-teal-500",
        addBtnText: "text-teal-600",
        addBtnHover: "hover:bg-teal-50",
        txBorderL: "border-l-teal-300",
        txBorderLHover: "hover:border-l-teal-400",
    },
    slate: {
        key: "slate",
        label: "Grigio",
        swatch: "bg-slate-500",
        swatchRing: "ring-slate-300",
        border: "border-l-slate-400",
        borderHover: "hover:border-l-slate-500",
        bg: "bg-slate-100",
        bgLight: "bg-slate-50/60",
        iconBg: "bg-slate-100",
        iconColor: "text-slate-600",
        progressBar: "bg-slate-500",
        addBtnText: "text-slate-600",
        addBtnHover: "hover:bg-slate-50",
        txBorderL: "border-l-slate-300",
        txBorderLHover: "hover:border-l-slate-400",
    },
};

const CATEGORY_TYPE_COLOR_MAP = {
    income: "emerald",
    expense: "rose",
    mixed: "slate",
};

export function getCategoryColorByType(type) {
    const colorKey = CATEGORY_TYPE_COLOR_MAP[type] || "slate";
    return CATEGORY_COLORS_MAP[colorKey] || CATEGORY_COLORS_MAP.slate;
}

export function getCategoryColor(colorKey, fallbackIndex = 0) {
    if (colorKey && CATEGORY_COLORS_MAP[colorKey]) {
        return CATEGORY_COLORS_MAP[colorKey];
    }
    const keys = CATEGORY_COLOR_KEYS;
    return CATEGORY_COLORS_MAP[keys[fallbackIndex % keys.length]];
}
